language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: "sgirardin-github"
    branches:
          - master
          - feature/*
          - correction/*
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  overwrite: true
  file:
    -"easyContent2Metadata-platform-jar-*.jar"
    -"easyContent2Metadata-share-jar-*.jar"
  skip_cleanup: true
  on:
    tags: false