version: '3.4'
services:
  easyContent2Metadata-share:
    image: alfresco-share-easyContent2Metadata:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../easyContent2Metadata-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8888"
      REPO_HOST: easyContent2Metadata-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  easyContent2Metadata-acs:
    image: alfresco-content-services-easyContent2Metadata:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../easyContent2Metadata-platform-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - easyContent2Metadata-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - easyContent2Metadata-postgres
  easyContent2Metadata-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    ports:
      - "${postgres.port}:5432"
    volumes:
      - easyContent2Metadata-db-volume:/var/lib/postgresql/data
  easyContent2Metadata-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: easyContent2Metadata-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: easyContent2Metadata-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - easyContent2Metadata-ass-volume:/opt/alfresco-search-services/contentstore
      - easyContent2Metadata-ass-volume:/opt/alfresco-search-services/data
volumes:
  easyContent2Metadata-acs-volume:
    external: true
  easyContent2Metadata-db-volume:
    external: true
  easyContent2Metadata-ass-volume:
    external: true